language: ruby
rvm:
  - 2.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - lftp

  ssh_known_hosts:
    - 45.33.18.250:54545
    - mirror.urda.cc:54545
    - walter.urda.cc:54545

branches:
  only:
    - gh-pages

install:
  - make install

script:
  - make travis

after_success:
  - openssl aes-256-cbc -K $encrypted_dd95c95167c0_key -iv $encrypted_dd95c95167c0_iv
    -in walter_deploy_id_rsa.enc -out walter_deploy_id_rsa -d
  - chmod 600 walter_deploy_id_rsa
  # - lftp -c
  #  "set sftp:connect-program \"ssh -a -x -p 54545 -i walter_deploy_id_rsa\";
  #  connect sftp://mirrorurdacc:usingsshkey@mirror.urda.cc;
  #  mirror --reverse --delete --verbose ./_site /public_html"
  - shred walter_deploy_id_rsa

notifications:
  email: false
  slack:
    secure: >
      PazZFbGsTfhTc9BKCdSpOwAGX9fuJTyCf4h8HIKGfCusPx5p8IeKX4GqhjYl5wMHwmy3dyUZ5s
      2UnCVuOz2+XBksM3lfmEPh1uoTR9EtrgwAR9XJFkDdhNVvlzzLnUCvZpH65iFM5sbVy5T9NTal
      5qmTwb2gdnP7gK2Lh0W+3TseRm55HM96bYNSRjtwYHtKAkCjuY/8YHWbNv3DmXNn+/Ekbsq724
      noZKEw1QUuDcfQMIDexpsBMv3iqDuOLi5PDfo89UMeqkjyIJEmw20236kuZb9acHoJKJcH50zL
      8JAenU4No25k/TcwH3s43jg4JC+LntCB5MiM2DVwuBJwyI1fmI7R7TAhCb8/jRt1JVIBok6rr6
      M1ryaTefG3dZNYiuLFN6h1Nf4ti+yfrTaWe48d76K2sJjh5jtA/wvS8DqcsZq9E1bSSBfODHPQ
      rYsGRfz50TunS3Yk6t17ZfQdX1mlzN6v4L5jfL4SwrWjme8UdPwktDFtbJegu5h6RYzMa8WNPE
      XCbSqXqtM2XjX0eS28Ey52jPoB5ZsATVIyr46zyRf/yW6/6Mmu51cONZY9CTGUqOtg4GZbU4Lz
      y+Xl6EDMSmnhZJ3VLgkBovJhMgay0FJjzWvxqF/Xq8/KnfLZN2bPEQ9RD8pHhPFF1Sw8MS9ywi
      Sw0ZeRmdP3t50E6Ho=
