#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Writings of Urda
author: Peter Urda

# Short bio or description (displayed in the header)
description: "A Kentuckian's thoughts on life, technology, and what have you"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /content/site-images/avatar-square.jpg

# Pagination Stuff
paginate: 10
paginate_path: "/blog/page/:num/"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  linkedin: urdap
  github: urda
  facebook: peter.urda
  twitter: urda
  flickr: urda
  rss: jekyll-feed
  # email:
  # dribbble:
  # pinterest:
  # instagram:
  # youtube: # channel/<your_long_string> or user/<user-name>
  # stackoverflow: users/169153/urda # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-65623105-3

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://urda.com/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

permalink: /blog/:year/:month/:day/:title

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - Makefile
    - README.md
    - walter_deploy_id_rsa.enc
