#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Writings of Urda
title: Writings of Urda
author: Peter Urda

# Short bio or description (displayed in the header)
description: "Your friendly West Coast Software Engineer"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/avatar/avatar-250.png

# Pagination Stuff
paginate: 10
paginate_path: "/blog/page/:num/"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: website@urda.com
  flickr: urda
  github: urda
  instagram: peter.urda
  linkedin: urda
  rss: jekyll-feed
  stackoverflow: users/169153/urda # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  twitter: urda

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Cloudflare Web Analytics Control
cloudflare_web_analytics_token: 87c9132d6cf2496f99c47a221a4ef7fc

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://urda.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'rougecssclass'

permalink: /blog/:year/:month/:day/:title

# The release of Jekyll Now that you're using
version: v1.1.0-urda

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - vendor/
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - website.sublime-project
  - website.sublime-workspace
