################################################################################
# Configuration
################################################################################

name: Writings of Urda
title: Writings of Urda
author: Peter Urda

# Your URL (e.g. https://urda.com or https://github.com/urda)
# Required for Sitemap.xml and RSS feed
url: https://urda.com

# Short bio or description to display in header
description: "Your friendly West Coast Software Engineer"

# URL for the avatar image
avatar: /assets/avatar/avatar-250.png

# Pagination Contorl
paginate: 10
paginate_path: "/blog/page/:num/"

################################################################################
# Optional Features and Settings
################################################################################

# Includes an icon in the footer for each username you enter
footer-links:
  email: website@urda.com
  flickr: urda
  github: urda
  instagram: peter.urda
  linkedin: urda
  rss: jekyll-feed
  stackoverflow: users/169153/urda # stackoverflow URL, e.g. "users/169153/urda"
  twitter: urda
  mastodon: https://urda.social/@urda

# Cloudflare Web Analytics Control
cloudflare_web_analytics_token: 87c9132d6cf2496f99c47a221a4ef7fc

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

################################################################################
#
# /!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\
# /!\ *STOP* Do not change things below! /!\
# /!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\/!\
#
################################################################################

version: v1.1.1-urda

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'rougecssclass'

permalink: /blog/:year/:month/:day/:title

sass:
  style: :compressed

plugins:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

include:
  - _pages

exclude:
  - vendor/
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - website.sublime-project
  - website.sublime-workspace
