version: '3'

services:
  builder:
    command: make jekyll-build
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./_site:/app/web/_site

  test:
    command: make travis-test
    build:
      context: .
      dockerfile: ./Dockerfile

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
