name: Linting urda.com


on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout ⬇️
        uses: actions/checkout@v5

      # https://github.com/marketplace/actions/setup-pnpm
      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false # pnpm install is ran if set to 'true'

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies via pnpm
        run: pnpm install

      - name: Version Check 🕵️
        run: make version-check

      - name: Lint 🧹
        run: make jekyll-lint
