name: Linting urda.com


on:
  workflow_call:


permissions:
  contents: read


jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: ⬇️ Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: ⚙️ Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: 🕵️ Version Check
        run: make jekyll-version-check

      - name: 🧹 Lint
        run: make jekyll-lint
