name: PR Check urda.com


on:
  pull_request:
    branches:
      - gh-pages


permissions:
  contents: read


jobs:
  lint:
    uses: ./.github/workflows/linting.yaml

  test:
    uses: ./.github/workflows/testing.yaml
