name: Testing urda.com


on:
  workflow_call:


permissions:
  contents: read


jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: ⬇️ Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: ⚙️ Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: 🧪 Test
        run: make jekyll-test
